DB_LOCATION = 'data/tickets_cache.db'
CSV_ROUTES_LOCATION = 'data/tutu_routes.csv'
FLIGHTS_ROUTES_LOCATION = 'data/openflights_routes.dat'
AIRPORTS_LOCATION = 'data/openflights_airports.dat'
CITIES_LOCATION = 'data/cities.json'
