"""add tutucache and aviasalescache tables

Revision ID: 2f9b65016dd7
Revises: 
Create Date: 2020-04-09 00:58:15.696015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9b65016dd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviasalescache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('origin_city', sa.String(), nullable=True),
    sa.Column('destination_city', sa.String(), nullable=True),
    sa.Column('depart_datetime', sa.DateTime(), nullable=True),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('obtained_datetime', sa.DateTime(), nullable=True),
    sa.Column('airline', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutucache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('origin_city', sa.String(), nullable=True),
    sa.Column('destination_city', sa.String(), nullable=True),
    sa.Column('depart_datetime', sa.DateTime(), nullable=True),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('obtained_datetime', sa.DateTime(), nullable=True),
    sa.Column('seat_type', sa.String(), nullable=True),
    sa.Column('seats_count', sa.Integer(), nullable=True),
    sa.Column('top_seats_price', sa.DECIMAL(), nullable=True),
    sa.Column('top_seats_count', sa.Integer(), nullable=True),
    sa.Column('bottom_seats_price', sa.DECIMAL(), nullable=True),
    sa.Column('bottom_seats_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('travel_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutucache')
    op.drop_table('aviasalescache')
    # ### end Alembic commands ###
