"""add is_empty column

Revision ID: 5a4825cec2de
Revises: f96ae2c4e2da
Create Date: 2020-04-30 01:10:20.493113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4825cec2de'
down_revision = 'f96ae2c4e2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aviasalescache', sa.Column('is_empty', sa.Boolean(), nullable=True))
    op.add_column('tutucache', sa.Column('is_empty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutucache', 'is_empty')
    op.drop_column('aviasalescache', 'is_empty')
    # ### end Alembic commands ###
