"""renaming cities columns to points

Revision ID: f96ae2c4e2da
Revises: c948edd99ef9
Create Date: 2020-04-28 01:55:11.070941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96ae2c4e2da'
down_revision = 'c948edd99ef9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('aviasalescache') as batch_op:
        batch_op.alter_column('destination_city', new_column_name='destination_point')
        batch_op.alter_column('origin_city', new_column_name='origin_point')
    with op.batch_alter_table('tutucache') as batch_op:
        batch_op.alter_column('destination_city', new_column_name='destination_point')
        batch_op.alter_column('origin_city', new_column_name='origin_point')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('aviasalescache', sa.Column('destination_point', sa.String(), nullable=True))
    # op.add_column('aviasalescache', sa.Column('origin_point', sa.String(), nullable=True))
    # op.drop_column('aviasalescache', 'destination_city')
    # op.drop_column('aviasalescache', 'origin_city')
    # op.add_column('tutucache', sa.Column('destination_point', sa.String(), nullable=True))
    # op.add_column('tutucache', sa.Column('origin_point', sa.String(), nullable=True))
    # op.drop_column('tutucache', 'destination_city')
    # op.drop_column('tutucache', 'origin_city')
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('aviasalescache') as batch_op:
        batch_op.alter_column('destination_point', new_column_name='destination_city')
        batch_op.alter_column('origin_point', new_column_name='origin_city')
    with op.batch_alter_table('tutucache') as batch_op:
        batch_op.alter_column('destination_point', new_column_name='destination_city')
        batch_op.alter_column('origin_point', new_column_name='origin_city')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tutucache', sa.Column('origin_city', sa.VARCHAR(), nullable=True))
    # op.add_column('tutucache', sa.Column('destination_city', sa.VARCHAR(), nullable=True))
    # op.drop_column('tutucache', 'origin_point')
    # op.drop_column('tutucache', 'destination_point')
    # op.add_column('aviasalescache', sa.Column('origin_city', sa.VARCHAR(), nullable=True))
    # op.add_column('aviasalescache', sa.Column('destination_city', sa.VARCHAR(), nullable=True))
    # op.drop_column('aviasalescache', 'origin_point')
    # op.drop_column('aviasalescache', 'destination_point')
    # ### end Alembic commands ###
